version: "3.9"

services:
  finance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-backend
    ports:
      - "8080:8080"  # Cambiar si tu app usa otro
    volumes:
      - db_data:/app/db       # Persistimos tus bases SQLite
    env_file:
      - .env                  # Cargamos tu archivo .env
    restart: unless-stopped

volumes:
  db_data:
